/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.UsuarioDAO;
import entidades.Usuario;
import javax.swing.JOptionPane;
import varios.TextPrompt;

/**
 *
 * @author usuario
 */
public class NuevaContraseña extends javax.swing.JDialog {

    private Usuario usuario;
    /**
     * Creates new form NewJDialog
     */
    public NuevaContraseña(java.awt.Frame parent, boolean modal,Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
        TextPrompt contraseña = new TextPrompt("Obligatorio", jPasswordField_Contraseña);
        TextPrompt contraseña1 = new TextPrompt("Obligatorio", jPasswordField_Repetir_Contraseña);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Contraseña = new javax.swing.JLabel();
        jLabel_RepetirContraseña = new javax.swing.JLabel();
        jPasswordField_Contraseña = new javax.swing.JPasswordField();
        jPasswordField_Repetir_Contraseña = new javax.swing.JPasswordField();
        jButton_Cambiar = new javax.swing.JButton();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Contraseña.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña.setFont(new java.awt.Font("Haettenschweiler", 1, 24)); // NOI18N
        jLabel_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña.setText("Nueva Contraseña");
        jPanel1.add(jLabel_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 40));

        jLabel_RepetirContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_RepetirContraseña.setFont(new java.awt.Font("Haettenschweiler", 1, 24)); // NOI18N
        jLabel_RepetirContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_RepetirContraseña.setText("Repetir Contraseña");
        jPanel1.add(jLabel_RepetirContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 40));

        jPasswordField_Contraseña.setBackground(new java.awt.Color(0, 51, 51));
        jPasswordField_Contraseña.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPasswordField_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_Contraseña.setToolTipText("");
        jPasswordField_Contraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jPasswordField_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 160, 40));

        jPasswordField_Repetir_Contraseña.setBackground(new java.awt.Color(0, 51, 51));
        jPasswordField_Repetir_Contraseña.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPasswordField_Repetir_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_Repetir_Contraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jPasswordField_Repetir_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 160, 40));

        jButton_Cambiar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Cambiar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jButton_Cambiar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cambiar.setText("Cambiar");
        jButton_Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CambiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 132, 40));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo_Nueva_Contraseña.png"))); // NOI18N
        jLabel_Fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -760, 410, 1050));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CambiarActionPerformed

        String contraseña = "";
        char[] paswrd = this.jPasswordField_Contraseña.getPassword();
        for (int i = 0; i < paswrd.length; i++) {
            contraseña += paswrd[i];
        }
        String contraseña1 = "";
        char[] paswrd1 = this.jPasswordField_Repetir_Contraseña.getPassword();
        for (int i = 0; i < paswrd1.length; i++) {
            contraseña1 += paswrd1[i];
        }
        if (contraseña.isEmpty() || contraseña1.isEmpty()) {
            JOptionPane.showConfirmDialog(this, "Los campos no pueden quedar vacios", "Información", JOptionPane.CLOSED_OPTION);
        } else if (contraseña.equals(contraseña1)) {
            int opcion = JOptionPane.showConfirmDialog(this, "Esta seguro de que '" + contraseña + "' sera tu nueva contraseña", "Información", JOptionPane.YES_NO_OPTION);
            if (opcion == 0) {
                usuario.setContraseña(contraseña);
                UsuarioDAO u = new UsuarioDAO();
                u.modificarUsuario(usuario);
                JOptionPane.showConfirmDialog(this, "Su contraseña se ha cambiado correctamente", "Información", JOptionPane.CLOSED_OPTION);
                this.dispose();
            } else {
                JOptionPane.showConfirmDialog(this, "Vuelva a introducirla entonces", "Información", JOptionPane.CLOSED_OPTION);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_CambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuario usuario = null;
                NuevaContraseña dialog = new NuevaContraseña(new javax.swing.JFrame(), true,usuario);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cambiar;
    private javax.swing.JLabel jLabel_Contraseña;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JLabel jLabel_RepetirContraseña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_Contraseña;
    private javax.swing.JPasswordField jPasswordField_Repetir_Contraseña;
    // End of variables declaration//GEN-END:variables
}
