/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.UsuarioDAO;
import entidades.Usuario;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import varios.TextPrompt;

/**
 *
 * @author usuario
 */
public class OlvidoContraseña extends javax.swing.JFrame {

    int intento;

    /**
     * Creates new form OlvidoContraseña
     */
    public OlvidoContraseña() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel_DIa.setVisible(false);
        jSpinner_Dia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Titulo_Recupertar = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabel_Apellido = new javax.swing.JLabel();
        jTextField_Apellido = new javax.swing.JTextField();
        jLabel_Email = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel_Nif = new javax.swing.JLabel();
        jTextField_NIF = new javax.swing.JTextField();
        jCheckBox_Robot = new javax.swing.JCheckBox();
        jLabel_DIa = new javax.swing.JLabel();
        jSpinner_Dia = new javax.swing.JSpinner();
        jButton_Recuperar = new javax.swing.JButton();
        jButton_Volver = new javax.swing.JButton();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo_Recupertar.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 60)); // NOI18N
        jLabel_Titulo_Recupertar.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Titulo_Recupertar.setText("Recuperación");
        jPanel1.add(jLabel_Titulo_Recupertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel_Nombre.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre.setText("Nombre");
        jPanel1.add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jTextField_Nombre.setBackground(new java.awt.Color(0, 51, 51));
        jTextField_Nombre.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jTextField_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 166, 33));

        jLabel_Apellido.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        jLabel_Apellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Apellido.setText("Apellido");
        jPanel1.add(jLabel_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jTextField_Apellido.setBackground(new java.awt.Color(0, 51, 51));
        jTextField_Apellido.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jTextField_Apellido.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Apellido.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jTextField_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 166, 33));

        jLabel_Email.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        jLabel_Email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Email.setText("Email");
        jPanel1.add(jLabel_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jTextField_Email.setBackground(new java.awt.Color(0, 51, 51));
        jTextField_Email.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jTextField_Email.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Email.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jTextField_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 197, 33));

        jLabel_Nif.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        jLabel_Nif.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nif.setText("NIF");
        jPanel1.add(jLabel_Nif, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jTextField_NIF.setBackground(new java.awt.Color(0, 51, 51));
        jTextField_NIF.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jTextField_NIF.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_NIF.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jTextField_NIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 166, 33));

        jCheckBox_Robot.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox_Robot.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_Robot.setText("No soy un robot");
        jCheckBox_Robot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_RobotActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox_Robot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, 30));

        jLabel_DIa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_DIa.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DIa.setText("Indica que dia es hoy");
        jPanel1.add(jLabel_DIa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jSpinner_Dia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jSpinner_Dia.setModel(new javax.swing.SpinnerNumberModel(0, 0, 31, 1));
        jSpinner_Dia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner_Dia.setOpaque(false);
        jPanel1.add(jSpinner_Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 50, -1));

        jButton_Recuperar.setBackground(new java.awt.Color(0, 51, 51));
        jButton_Recuperar.setFont(new java.awt.Font("Eras Demi ITC", 1, 20)); // NOI18N
        jButton_Recuperar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Recuperar.setText("Recuperar");
        jButton_Recuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RecuperarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Recuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 163, 38));

        jButton_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Volver_verde.png"))); // NOI18N
        jButton_Volver.setContentAreaFilled(false);
        jButton_Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo_Recuperacion.jpg"))); // NOI18N
        jLabel_Fondo.setText("jLabel7");
        jPanel1.add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -300, 620, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_RobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_RobotActionPerformed
        String nombre = this.jTextField_Nombre.getText();
        String apellido = this.jTextField_Apellido.getText();
        String email = this.jTextField_Email.getText();
        String nif = this.jTextField_NIF.getText();
        if ((nombre.isEmpty()) || (apellido.isEmpty()) || (email.isEmpty()) || (nif.isEmpty())) {
            jCheckBox_Robot.setSelected(false);
            JOptionPane.showConfirmDialog(this, "Antes,todos los campos tienen que estar rellenados", "Información", JOptionPane.CLOSED_OPTION);
        } else if (jCheckBox_Robot.isSelected()) {
            jLabel_DIa.setVisible(true);
            jSpinner_Dia.setVisible(true);
        } else {
            jLabel_DIa.setVisible(false);
            jSpinner_Dia.setVisible(false);
        }

    }//GEN-LAST:event_jCheckBox_RobotActionPerformed


    private void jButton_RecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RecuperarActionPerformed
        
        String nombre = this.jTextField_Nombre.getText();
        String apellido = this.jTextField_Apellido.getText();
        String email = this.jTextField_Email.getText();
        String nif = this.jTextField_NIF.getText();
        if ((nombre.isEmpty()) || (apellido.isEmpty()) || (email.isEmpty()) || (nif.isEmpty())) {
            if ((nombre.isEmpty()) && (apellido.isEmpty()) && (email.isEmpty()) && (nif.isEmpty())) {
                JOptionPane.showConfirmDialog(this, "Los campos no pueden quedar vacios", "Información", JOptionPane.CLOSED_OPTION);
            } else {
                this.jTextField_Nombre.setText("");
                this.jTextField_Apellido.setText("");
                this.jTextField_Email.setText("");
                this.jTextField_NIF.setText("");
                if (nombre.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Nombre no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (apellido.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Apellido no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (email.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Email no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (nif.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo NIF no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
            }
        } else if (jCheckBox_Robot.isSelected()) {
            Calendar c = new GregorianCalendar();
            String diahoy = Integer.toString(c.get(Calendar.DATE));
            String diausuario = jSpinner_Dia.getValue().toString();
            if (diahoy.equals(diausuario)) {
                Boolean valido = Usuario.buscarUsuarioporNombreApellidoEmailNIF(nombre, apellido, email, nif);
                if (valido) {
                    Usuario usuario = new Usuario();
                    usuario = Usuario.buscarUsuarioporEmail(email);                
                    NuevaContraseña nuevacontraseña = new NuevaContraseña(this, false,usuario);
                    nuevacontraseña.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Los datos introducidos no son correctos.\nPor lo tanto no es suficiente para recuperar la contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
                    Inicio inicio = new Inicio();
                    inicio.setVisible(true);
                    this.dispose();
                }
            } else if (intento < 1) {
                JOptionPane.showConfirmDialog(this, "Dia incorrecto,tiene otro intento", "Información", JOptionPane.CLOSED_OPTION);
                intento++;
            } else if (intento == 1) {
                JOptionPane.showMessageDialog(this, "Dia incorecto", "Error", JOptionPane.ERROR_MESSAGE);
                Inicio inicio = new Inicio();
                inicio.setVisible(true);
                this.dispose();
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Debe seleccionar que no es un robot", "Información", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_jButton_RecuperarActionPerformed

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OlvidoContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Recuperar;
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JCheckBox jCheckBox_Robot;
    private javax.swing.JLabel jLabel_Apellido;
    private javax.swing.JLabel jLabel_DIa;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JLabel jLabel_Nif;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Titulo_Recupertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner_Dia;
    private javax.swing.JTextField jTextField_Apellido;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_NIF;
    private javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
