/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.BancarioDAO;
import dao.DireccionDAO;
import dao.UsuarioDAO;
import entidades.Bancario;
import entidades.Direccion;
import entidades.Usuario;
import java.awt.event.ItemEvent;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public RegistroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel_Registro_cruz_roja.setVisible(false);
        jLabel_Registro_cruz_roja1.setVisible(false);
        jLabel_Registro_cruz_roja2.setVisible(false);
        jLabel_Registro_cruz_roja3.setVisible(false);
        jLabel_Registro_cruz_roja4.setVisible(false);
        jLabel_Registro_cruz_roja5.setVisible(false);
        jLabel_tick_verde.setVisible(false);
        jLabel_Registro_tick_verde1.setVisible(false);
        jLabel_Registro_tick_verde2.setVisible(false);
        jLabel_Registro_tick_verde3.setVisible(false);
        jLabel_Registro_tick_verde4.setVisible(false);
        jLabel_Registro_tick_verde5.setVisible(false);
        jPanel_Bienvenida.setVisible(true);
        jPanel_Bienvenida.setEnabled(true);
        jPanel_Datos_Personales.setEnabled(false);
        jPanel_Datos_Personales.setVisible(false);
        jPanel_Direccion.setEnabled(false);
        jPanel_Direccion.setVisible(false);
        jPanel_Datos_Bancarios.setEnabled(false);
        jPanel_Datos_Bancarios.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tick_verde6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jPanel_Datos_Bancarios = new javax.swing.JPanel();
        jLabel_Registro_Titular_Tarjeta = new javax.swing.JLabel();
        jLabel_Registro_Numero_Tarjeta = new javax.swing.JLabel();
        jLabel_Registro_Titular_Codigo_Tarjeta = new javax.swing.JLabel();
        jTextField_Registro_Titular_Tarjeta = new javax.swing.JTextField();
        jTextField_Registro_Numero_Tarjeta = new javax.swing.JTextField();
        jTextField_Registro_Numero_Tarjeta1 = new javax.swing.JTextField();
        jTextField_Registro_Numero_Tarjeta2 = new javax.swing.JTextField();
        jTextField_Registro_Numero_Tarjeta3 = new javax.swing.JTextField();
        jTextField_Registro_Codigo_Tarjeta = new javax.swing.JTextField();
        jButton_Registro_Volver1 = new javax.swing.JButton();
        jCheckBox_Registro_Aceptar_Terminos = new javax.swing.JCheckBox();
        jButton_Registro_Registrarse1 = new javax.swing.JButton();
        jLabel_Registro_Datos_Opcionales = new javax.swing.JLabel();
        jPanel_Direccion = new javax.swing.JPanel();
        jLabel_Registro_Calle = new javax.swing.JLabel();
        jLabel_Registro_Portal = new javax.swing.JLabel();
        jLabel_Registro_Municipio = new javax.swing.JLabel();
        jLabel_Registro_Piso = new javax.swing.JLabel();
        jLabel_Registro_Codigo_Postal = new javax.swing.JLabel();
        jLabel_Registro_Pais = new javax.swing.JLabel();
        jLabel_Registro_Codigo_Ciudad = new javax.swing.JLabel();
        jTextField_Registro_Calle = new javax.swing.JTextField();
        jTextField_Registro_Portal = new javax.swing.JTextField();
        jTextField_Registro_Municipio = new javax.swing.JTextField();
        jTextField_Registro_Piso = new javax.swing.JTextField();
        jTextField_Registro_Codigo_Postal = new javax.swing.JTextField();
        jComboBox_Registro_País = new javax.swing.JComboBox<>();
        jComboBox_Registro_Ciudad = new javax.swing.JComboBox<>();
        jButton_Registro_Volver = new javax.swing.JButton();
        jButton_Registro_Suiguiente = new javax.swing.JButton();
        jPanel_Datos_Personales = new javax.swing.JPanel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Registro_Apellido = new javax.swing.JLabel();
        jLabel_Registro_Email = new javax.swing.JLabel();
        jLabel_Registro_NIF = new javax.swing.JLabel();
        jLabel_Registro_Contraseña = new javax.swing.JLabel();
        jLabel_Registro_Contraseña1 = new javax.swing.JLabel();
        jTextField_Registro_Nombre = new javax.swing.JTextField();
        jTextField_Registro_Apellido = new javax.swing.JTextField();
        jTextField_Registro_Email = new javax.swing.JTextField();
        jTextField_Registro_NIF = new javax.swing.JTextField();
        jPasswordField_Registro_Contraseña = new javax.swing.JPasswordField();
        jPasswordField_Registro_Contraseña1 = new javax.swing.JPasswordField();
        jLabel_Registro_NombreCorrecto = new javax.swing.JLabel();
        jLabel_Registro_ApellidoCorrecto = new javax.swing.JLabel();
        jLabel_Registro_EmailCorrecto = new javax.swing.JLabel();
        jLabel_Registro_NifCorrecto = new javax.swing.JLabel();
        jLabel_Registro_ContraseñaCorrecto = new javax.swing.JLabel();
        jLabel_tick_verde = new javax.swing.JLabel();
        jLabel_Registro_tick_verde1 = new javax.swing.JLabel();
        jLabel_Registro_tick_verde2 = new javax.swing.JLabel();
        jLabel_Registro_tick_verde3 = new javax.swing.JLabel();
        jLabel_Registro_tick_verde4 = new javax.swing.JLabel();
        jLabel_Registro_tick_verde5 = new javax.swing.JLabel();
        jLabel_Registro_cruz_roja = new javax.swing.JLabel();
        jLabel_Registro_cruz_roja1 = new javax.swing.JLabel();
        jLabel_Registro_cruz_roja2 = new javax.swing.JLabel();
        jLabel_Registro_cruz_roja3 = new javax.swing.JLabel();
        jLabel_Registro_cruz_roja4 = new javax.swing.JLabel();
        jLabel_Registro_cruz_roja5 = new javax.swing.JLabel();
        jButton_Registro_Siguiente = new javax.swing.JButton();
        jPanel_Bienvenida = new javax.swing.JPanel();
        jButton_Registro_Direccion = new javax.swing.JButton();
        jButton_Registro_Datos_Personales = new javax.swing.JButton();
        jLabe_lRegistro_Linea1 = new javax.swing.JLabel();
        jLabel_Registro_Linea2 = new javax.swing.JLabel();
        jLabel_Registro_Linea3 = new javax.swing.JLabel();
        jLabel_Registro_Linea5 = new javax.swing.JLabel();
        jLabel_Registro_Linea6 = new javax.swing.JLabel();
        jLabel_Registro_Linea7 = new javax.swing.JLabel();
        jButton_Registro_Empezar = new javax.swing.JButton();
        jLabel_Registro_Linea4 = new javax.swing.JLabel();
        jButton_Registro_Datos_Bancarios = new javax.swing.JButton();
        jButton_Registro_Volver_Inicio = new javax.swing.JButton();
        jLabel_Registro_Fondo = new javax.swing.JLabel();

        jLabel_tick_verde6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick_verde.png"))); // NOI18N
        jLabel_tick_verde6.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jPanel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Impact", 1, 60)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("REGISTRO DE USUARIO");
        jPanel1.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jPanel_Datos_Bancarios.setBackground(new java.awt.Color(35, 45, 68));
        jPanel_Datos_Bancarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Registro_Titular_Tarjeta.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Titular_Tarjeta.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Titular_Tarjeta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Registro_Titular_Tarjeta.setText("Titular tarjeta");
        jPanel_Datos_Bancarios.add(jLabel_Registro_Titular_Tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 160, -1));

        jLabel_Registro_Numero_Tarjeta.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Numero_Tarjeta.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Numero_Tarjeta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Registro_Numero_Tarjeta.setText("Número tarjeta");
        jPanel_Datos_Bancarios.add(jLabel_Registro_Numero_Tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 180, -1));

        jLabel_Registro_Titular_Codigo_Tarjeta.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Titular_Codigo_Tarjeta.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Titular_Codigo_Tarjeta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Registro_Titular_Codigo_Tarjeta.setText("Titular tarjeta");
        jPanel_Datos_Bancarios.add(jLabel_Registro_Titular_Codigo_Tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 160, -1));

        jTextField_Registro_Titular_Tarjeta.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Titular_Tarjeta.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Titular_Tarjeta.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Titular_Tarjeta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Titular_Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_Titular_TarjetaActionPerformed(evt);
            }
        });
        jTextField_Registro_Titular_Tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_Titular_TarjetaKeyReleased(evt);
            }
        });
        jPanel_Datos_Bancarios.add(jTextField_Registro_Titular_Tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 220, 30));

        jTextField_Registro_Numero_Tarjeta.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Numero_Tarjeta.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Numero_Tarjeta.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Numero_Tarjeta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Numero_Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_Numero_TarjetaActionPerformed(evt);
            }
        });
        jTextField_Registro_Numero_Tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_Numero_TarjetaKeyReleased(evt);
            }
        });
        jPanel_Datos_Bancarios.add(jTextField_Registro_Numero_Tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 70, 30));

        jTextField_Registro_Numero_Tarjeta1.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Numero_Tarjeta1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Numero_Tarjeta1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Numero_Tarjeta1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Numero_Tarjeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_Numero_Tarjeta1ActionPerformed(evt);
            }
        });
        jTextField_Registro_Numero_Tarjeta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_Numero_Tarjeta1KeyReleased(evt);
            }
        });
        jPanel_Datos_Bancarios.add(jTextField_Registro_Numero_Tarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 70, 30));

        jTextField_Registro_Numero_Tarjeta2.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Numero_Tarjeta2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Numero_Tarjeta2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Numero_Tarjeta2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Numero_Tarjeta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_Numero_Tarjeta2ActionPerformed(evt);
            }
        });
        jTextField_Registro_Numero_Tarjeta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_Numero_Tarjeta2KeyReleased(evt);
            }
        });
        jPanel_Datos_Bancarios.add(jTextField_Registro_Numero_Tarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 70, 30));

        jTextField_Registro_Numero_Tarjeta3.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Numero_Tarjeta3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Numero_Tarjeta3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Numero_Tarjeta3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Numero_Tarjeta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_Numero_Tarjeta3ActionPerformed(evt);
            }
        });
        jTextField_Registro_Numero_Tarjeta3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_Numero_Tarjeta3KeyReleased(evt);
            }
        });
        jPanel_Datos_Bancarios.add(jTextField_Registro_Numero_Tarjeta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 70, 30));

        jTextField_Registro_Codigo_Tarjeta.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Codigo_Tarjeta.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Codigo_Tarjeta.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Codigo_Tarjeta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Codigo_Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_Codigo_TarjetaActionPerformed(evt);
            }
        });
        jTextField_Registro_Codigo_Tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_Codigo_TarjetaKeyReleased(evt);
            }
        });
        jPanel_Datos_Bancarios.add(jTextField_Registro_Codigo_Tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 70, 30));

        jButton_Registro_Volver1.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Registro_Volver1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jButton_Registro_Volver1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registro_Volver1.setText("Volver");
        jButton_Registro_Volver1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Registro_Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registro_Volver1ActionPerformed(evt);
            }
        });
        jPanel_Datos_Bancarios.add(jButton_Registro_Volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        jCheckBox_Registro_Aceptar_Terminos.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_Registro_Aceptar_Terminos.setText("He leído y acepto los términos y condiciones de uso");
        jCheckBox_Registro_Aceptar_Terminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_Registro_Aceptar_TerminosActionPerformed(evt);
            }
        });
        jPanel_Datos_Bancarios.add(jCheckBox_Registro_Aceptar_Terminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jButton_Registro_Registrarse1.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Registro_Registrarse1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jButton_Registro_Registrarse1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registro_Registrarse1.setText("Registrarse");
        jButton_Registro_Registrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registro_Registrarse1ActionPerformed(evt);
            }
        });
        jPanel_Datos_Bancarios.add(jButton_Registro_Registrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 160, 40));

        jLabel_Registro_Datos_Opcionales.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_Registro_Datos_Opcionales.setText("Datos opcionales");
        jPanel_Datos_Bancarios.add(jLabel_Registro_Datos_Opcionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jPanel1.add(jPanel_Datos_Bancarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 810, 430));

        jPanel_Direccion.setBackground(new java.awt.Color(35, 45, 68));
        jPanel_Direccion.setEnabled(false);
        jPanel_Direccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Registro_Calle.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Calle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Calle.setText("Calle");
        jPanel_Direccion.add(jLabel_Registro_Calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, -1));

        jLabel_Registro_Portal.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Portal.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Portal.setText("Portal");
        jPanel_Direccion.add(jLabel_Registro_Portal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jLabel_Registro_Municipio.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Municipio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Municipio.setText("Municipio");
        jPanel_Direccion.add(jLabel_Registro_Municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel_Registro_Piso.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Piso.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Piso.setText("Piso");
        jPanel_Direccion.add(jLabel_Registro_Piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel_Registro_Codigo_Postal.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Codigo_Postal.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Codigo_Postal.setText("Codigo Postal");
        jPanel_Direccion.add(jLabel_Registro_Codigo_Postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel_Registro_Pais.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Pais.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Pais.setText("País");
        jPanel_Direccion.add(jLabel_Registro_Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel_Registro_Codigo_Ciudad.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Codigo_Ciudad.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Codigo_Ciudad.setText("Ciudad");
        jPanel_Direccion.add(jLabel_Registro_Codigo_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        jTextField_Registro_Calle.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Calle.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Calle.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Calle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_CalleActionPerformed(evt);
            }
        });
        jTextField_Registro_Calle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_CalleKeyReleased(evt);
            }
        });
        jPanel_Direccion.add(jTextField_Registro_Calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 270, 30));

        jTextField_Registro_Portal.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Portal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Portal.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Portal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Portal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_PortalActionPerformed(evt);
            }
        });
        jTextField_Registro_Portal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_PortalKeyReleased(evt);
            }
        });
        jPanel_Direccion.add(jTextField_Registro_Portal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 40, 30));

        jTextField_Registro_Municipio.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Municipio.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Municipio.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Municipio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_MunicipioActionPerformed(evt);
            }
        });
        jTextField_Registro_Municipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_MunicipioKeyReleased(evt);
            }
        });
        jPanel_Direccion.add(jTextField_Registro_Municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 160, 30));

        jTextField_Registro_Piso.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Piso.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Piso.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Piso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Piso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_PisoActionPerformed(evt);
            }
        });
        jTextField_Registro_Piso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_PisoKeyReleased(evt);
            }
        });
        jPanel_Direccion.add(jTextField_Registro_Piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 90, 30));

        jTextField_Registro_Codigo_Postal.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Codigo_Postal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Codigo_Postal.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Codigo_Postal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Codigo_Postal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_Codigo_PostalActionPerformed(evt);
            }
        });
        jTextField_Registro_Codigo_Postal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_Codigo_PostalKeyReleased(evt);
            }
        });
        jPanel_Direccion.add(jTextField_Registro_Codigo_Postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 130, 30));

        jComboBox_Registro_País.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox_Registro_País.setMaximumRowCount(4);
        jComboBox_Registro_País.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Bélgica", "España", "Andorra", "Francia", "Alemania", "Portugal", "Argentina", "Mexico", "Brasil" }));
        jComboBox_Registro_País.setToolTipText("");
        jComboBox_Registro_País.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_Registro_PaísItemStateChanged(evt);
            }
        });
        jComboBox_Registro_País.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Registro_PaísActionPerformed(evt);
            }
        });
        jPanel_Direccion.add(jComboBox_Registro_País, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jComboBox_Registro_Ciudad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox_Registro_Ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Elija País--" }));
        jComboBox_Registro_Ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_Registro_CiudadMouseClicked(evt);
            }
        });
        jComboBox_Registro_Ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Registro_CiudadActionPerformed(evt);
            }
        });
        jPanel_Direccion.add(jComboBox_Registro_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 140, -1));

        jButton_Registro_Volver.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Registro_Volver.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jButton_Registro_Volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registro_Volver.setText("Volver");
        jButton_Registro_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registro_VolverActionPerformed(evt);
            }
        });
        jPanel_Direccion.add(jButton_Registro_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        jButton_Registro_Suiguiente.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Registro_Suiguiente.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jButton_Registro_Suiguiente.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registro_Suiguiente.setText("Siguiente");
        jButton_Registro_Suiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registro_SuiguienteActionPerformed(evt);
            }
        });
        jPanel_Direccion.add(jButton_Registro_Suiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 130, 40));

        jPanel1.add(jPanel_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 810, 430));

        jPanel_Datos_Personales.setBackground(new java.awt.Color(35, 45, 68));
        jPanel_Datos_Personales.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jPanel_Datos_Personales.setEnabled(false);
        jPanel_Datos_Personales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Nombre.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre.setText("Nombre");
        jPanel_Datos_Personales.add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel_Registro_Apellido.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Apellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Apellido.setText("Apellido");
        jPanel_Datos_Personales.add(jLabel_Registro_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel_Registro_Email.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Email.setText("Email");
        jPanel_Datos_Personales.add(jLabel_Registro_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel_Registro_NIF.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_NIF.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_NIF.setText("NIF");
        jPanel_Datos_Personales.add(jLabel_Registro_NIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel_Registro_Contraseña.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Contraseña.setText("Contraseña");
        jLabel_Registro_Contraseña.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel_Registro_Contraseña1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel_Registro_Contraseña1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registro_Contraseña1.setText("Repetir Contraseña");
        jLabel_Registro_Contraseña1.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jTextField_Registro_Nombre.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Nombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_NombreActionPerformed(evt);
            }
        });
        jTextField_Registro_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_NombreKeyReleased(evt);
            }
        });
        jPanel_Datos_Personales.add(jTextField_Registro_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 160, 30));

        jTextField_Registro_Apellido.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Apellido.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Apellido.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Apellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Registro_ApellidoActionPerformed(evt);
            }
        });
        jTextField_Registro_Apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_ApellidoKeyReleased(evt);
            }
        });
        jPanel_Datos_Personales.add(jTextField_Registro_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 160, 30));

        jTextField_Registro_Email.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_Email.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_Email.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_Email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_EmailKeyReleased(evt);
            }
        });
        jPanel_Datos_Personales.add(jTextField_Registro_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 190, 30));

        jTextField_Registro_NIF.setBackground(new java.awt.Color(0, 102, 102));
        jTextField_Registro_NIF.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextField_Registro_NIF.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Registro_NIF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Registro_NIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Registro_NIFKeyReleased(evt);
            }
        });
        jPanel_Datos_Personales.add(jTextField_Registro_NIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 150, 30));

        jPasswordField_Registro_Contraseña.setBackground(new java.awt.Color(0, 102, 102));
        jPasswordField_Registro_Contraseña.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPasswordField_Registro_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_Registro_Contraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Datos_Personales.add(jPasswordField_Registro_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 150, 30));

        jPasswordField_Registro_Contraseña1.setBackground(new java.awt.Color(0, 102, 102));
        jPasswordField_Registro_Contraseña1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jPasswordField_Registro_Contraseña1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_Registro_Contraseña1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Datos_Personales.add(jPasswordField_Registro_Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 150, 30));

        jLabel_Registro_NombreCorrecto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Registro_NombreCorrecto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_Datos_Personales.add(jLabel_Registro_NombreCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 350, 30));

        jLabel_Registro_ApellidoCorrecto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Registro_ApellidoCorrecto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_Datos_Personales.add(jLabel_Registro_ApellidoCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 350, 30));

        jLabel_Registro_EmailCorrecto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Registro_EmailCorrecto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_Datos_Personales.add(jLabel_Registro_EmailCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 320, 30));

        jLabel_Registro_NifCorrecto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Registro_NifCorrecto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_Datos_Personales.add(jLabel_Registro_NifCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 360, 30));

        jLabel_Registro_ContraseñaCorrecto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Registro_ContraseñaCorrecto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_Datos_Personales.add(jLabel_Registro_ContraseñaCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 360, 30));

        jLabel_tick_verde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick_verde.png"))); // NOI18N
        jLabel_tick_verde.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_tick_verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel_Registro_tick_verde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick_verde.png"))); // NOI18N
        jLabel_Registro_tick_verde1.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_tick_verde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel_Registro_tick_verde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick_verde.png"))); // NOI18N
        jLabel_Registro_tick_verde2.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_tick_verde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel_Registro_tick_verde3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick_verde.png"))); // NOI18N
        jLabel_Registro_tick_verde3.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_tick_verde3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel_Registro_tick_verde4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick_verde.png"))); // NOI18N
        jLabel_Registro_tick_verde4.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_tick_verde4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jLabel_Registro_tick_verde5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick_verde.png"))); // NOI18N
        jLabel_Registro_tick_verde5.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_tick_verde5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jLabel_Registro_cruz_roja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error_rojo.png"))); // NOI18N
        jLabel_Registro_cruz_roja.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_cruz_roja, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel_Registro_cruz_roja1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error_rojo.png"))); // NOI18N
        jLabel_Registro_cruz_roja1.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_cruz_roja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel_Registro_cruz_roja2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error_rojo.png"))); // NOI18N
        jLabel_Registro_cruz_roja2.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_cruz_roja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel_Registro_cruz_roja3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error_rojo.png"))); // NOI18N
        jLabel_Registro_cruz_roja3.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_cruz_roja3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel_Registro_cruz_roja4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error_rojo.png"))); // NOI18N
        jLabel_Registro_cruz_roja4.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_cruz_roja4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jLabel_Registro_cruz_roja5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error_rojo.png"))); // NOI18N
        jLabel_Registro_cruz_roja5.setToolTipText("");
        jPanel_Datos_Personales.add(jLabel_Registro_cruz_roja5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jButton_Registro_Siguiente.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Registro_Siguiente.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jButton_Registro_Siguiente.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registro_Siguiente.setText("Siguiente");
        jButton_Registro_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registro_SiguienteActionPerformed(evt);
            }
        });
        jPanel_Datos_Personales.add(jButton_Registro_Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 140, 40));

        jPanel1.add(jPanel_Datos_Personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 810, 430));

        jPanel_Bienvenida.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jPanel_Bienvenida.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        jPanel_Bienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Registro_Direccion.setBackground(new java.awt.Color(51, 0, 204));
        jButton_Registro_Direccion.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jButton_Registro_Direccion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registro_Direccion.setText("Dirección");
        jButton_Registro_Direccion.setContentAreaFilled(false);
        jButton_Registro_Direccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Registro_Direccion.setOpaque(true);
        jButton_Registro_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registro_DireccionActionPerformed(evt);
            }
        });
        jPanel_Bienvenida.add(jButton_Registro_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 210, 40));

        jButton_Registro_Datos_Personales.setBackground(new java.awt.Color(51, 0, 204));
        jButton_Registro_Datos_Personales.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jButton_Registro_Datos_Personales.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registro_Datos_Personales.setText("Datos Personales");
        jButton_Registro_Datos_Personales.setContentAreaFilled(false);
        jButton_Registro_Datos_Personales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Registro_Datos_Personales.setOpaque(true);
        jButton_Registro_Datos_Personales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registro_Datos_PersonalesActionPerformed(evt);
            }
        });
        jPanel_Bienvenida.add(jButton_Registro_Datos_Personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        jLabe_lRegistro_Linea1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabe_lRegistro_Linea1.setText("Bienevenido al registro de JML Conciertos:");
        jPanel_Bienvenida.add(jLabe_lRegistro_Linea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 500, 30));

        jLabel_Registro_Linea2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_Registro_Linea2.setText("1.Rellene sus datos personales.");
        jPanel_Bienvenida.add(jLabel_Registro_Linea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel_Registro_Linea3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_Registro_Linea3.setText("2.Rellene su direccion.");
        jPanel_Bienvenida.add(jLabel_Registro_Linea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel_Registro_Linea5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_Registro_Linea5.setText("4.Acepte los terminos de privacidad.");
        jPanel_Bienvenida.add(jLabel_Registro_Linea5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel_Registro_Linea6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_Registro_Linea6.setText("5.Click en registrar y todo listo.");
        jPanel_Bienvenida.add(jLabel_Registro_Linea6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jLabel_Registro_Linea7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Registro_Linea7.setText("Muchas gracias por confiar en JML Conciertos.Esperemos que sea de su agrado.");
        jPanel_Bienvenida.add(jLabel_Registro_Linea7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, 20));

        jButton_Registro_Empezar.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Registro_Empezar.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jButton_Registro_Empezar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registro_Empezar.setText("Empezar");
        jButton_Registro_Empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registro_EmpezarActionPerformed(evt);
            }
        });
        jPanel_Bienvenida.add(jButton_Registro_Empezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 140, 40));

        jLabel_Registro_Linea4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_Registro_Linea4.setText("3.Rellene sus datos bancarios(opcional).");
        jPanel_Bienvenida.add(jLabel_Registro_Linea4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jButton_Registro_Datos_Bancarios.setBackground(new java.awt.Color(51, 0, 204));
        jButton_Registro_Datos_Bancarios.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jButton_Registro_Datos_Bancarios.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registro_Datos_Bancarios.setText("Datos Bancarios");
        jButton_Registro_Datos_Bancarios.setContentAreaFilled(false);
        jButton_Registro_Datos_Bancarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Registro_Datos_Bancarios.setOpaque(true);
        jButton_Registro_Datos_Bancarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registro_Datos_BancariosActionPerformed(evt);
            }
        });
        jPanel_Bienvenida.add(jButton_Registro_Datos_Bancarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 300, 40));

        jPanel1.add(jPanel_Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 810, 470));

        jButton_Registro_Volver_Inicio.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton_Registro_Volver_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Volver_verde.png"))); // NOI18N
        jButton_Registro_Volver_Inicio.setContentAreaFilled(false);
        jButton_Registro_Volver_Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Registro_Volver_Inicio.setVerifyInputWhenFocusTarget(false);
        jButton_Registro_Volver_Inicio.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton_Registro_Volver_Inicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Registro_Volver_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registro_Volver_InicioActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Registro_Volver_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 80, -1));

        jLabel_Registro_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo_Registro.jpg"))); // NOI18N
        jPanel1.add(jLabel_Registro_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 950, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Registro_Volver_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registro_Volver_InicioActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_Registro_Volver_InicioActionPerformed

    private void jTextField_Registro_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_ApellidoActionPerformed

    private void jTextField_Registro_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_NombreActionPerformed

    private void jTextField_Registro_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_NombreKeyReleased
        String nombre = this.jTextField_Registro_Nombre.getText();
        jLabel_tick_verde.setVisible(false);
        jLabel_Registro_cruz_roja.setVisible(false);
        if (nombre.isEmpty()) {
            this.jLabel_Registro_NombreCorrecto.setText("");
        } else if ((nombre.length() < 3)) {
            jLabel_Registro_cruz_roja.setVisible(true);
            this.jLabel_Registro_NombreCorrecto.setText("Debe de contener al menos 3 caracteres");
        } else {
            this.jLabel_Registro_NombreCorrecto.setText("");
            if ((nombre.length() > 13)) {
                this.jLabel_Registro_NombreCorrecto.setText("No puede contener mas de 13 caracteres");
                jLabel_Registro_cruz_roja.setVisible(true);
            } else {
                this.jLabel_Registro_NombreCorrecto.setText("");
                if (nombre.matches(".*[^a-z-A-Z].*")) {
                    this.jLabel_Registro_NombreCorrecto.setText("No puede contener caracteres especiales");
                    jLabel_Registro_cruz_roja.setVisible(true);
                } else {
                    this.jLabel_Registro_NombreCorrecto.setText("Correcto");
                    jLabel_Registro_cruz_roja.setVisible(false);
                    jLabel_tick_verde.setVisible(true);
                }
            }

        }
    }//GEN-LAST:event_jTextField_Registro_NombreKeyReleased

    private void jTextField_Registro_ApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_ApellidoKeyReleased
        String apellido = this.jTextField_Registro_Apellido.getText();
        jLabel_Registro_tick_verde1.setVisible(false);
        jLabel_Registro_cruz_roja1.setVisible(false);
        if (apellido.isEmpty()) {
            this.jLabel_Registro_ApellidoCorrecto.setText("");
        } else if ((apellido.length() < 2)) {
            jLabel_Registro_cruz_roja1.setVisible(true);
            this.jLabel_Registro_ApellidoCorrecto.setText("Debe de contener al menos 2 caracteres");
        } else {
            this.jLabel_Registro_ApellidoCorrecto.setText("");
            if ((apellido.length() > 13)) {
                this.jLabel_Registro_ApellidoCorrecto.setText("No puede contener mas de 13 caracteres");
                jLabel_Registro_cruz_roja1.setVisible(true);
            } else {
                this.jLabel_Registro_ApellidoCorrecto.setText("");
                if (apellido.matches(".*[^a-z-A-Z].*")) {
                    this.jLabel_Registro_ApellidoCorrecto.setText("No puede contener caracteres especiales");
                    jLabel_Registro_cruz_roja1.setVisible(true);
                } else {
                    this.jLabel_Registro_ApellidoCorrecto.setText("Correcto");
                    jLabel_Registro_cruz_roja1.setVisible(false);
                    jLabel_Registro_tick_verde1.setVisible(true);
                }
            }

        }
    }//GEN-LAST:event_jTextField_Registro_ApellidoKeyReleased

    private void jTextField_Registro_EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_EmailKeyReleased
        String email = this.jTextField_Registro_Email.getText();
        Boolean valido = Usuario.validarEmail(email);
        jLabel_Registro_tick_verde2.setVisible(false);
        jLabel_Registro_cruz_roja2.setVisible(false);
        if (email.isEmpty()) {
            this.jLabel_Registro_EmailCorrecto.setText("");
        } else if (!valido) {
            jLabel_Registro_cruz_roja2.setVisible(true);
            this.jLabel_Registro_EmailCorrecto.setText("El formato debe ser algo@dominio.es/com");
        } else if ((email.length() > 25)) {
            this.jLabel_Registro_EmailCorrecto.setText("No puede contener mas de 25 caracteres");
            jLabel_Registro_cruz_roja2.setVisible(true);
        } else {
            this.jLabel_Registro_EmailCorrecto.setText("Correcto");
            jLabel_Registro_cruz_roja2.setVisible(false);
            jLabel_Registro_tick_verde2.setVisible(true);

        }
    }//GEN-LAST:event_jTextField_Registro_EmailKeyReleased

    private void jTextField_Registro_NIFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_NIFKeyReleased

        String nif = this.jTextField_Registro_NIF.getText();
        jLabel_Registro_tick_verde3.setVisible(false);
        jLabel_Registro_cruz_roja3.setVisible(false);
        if (nif.isEmpty()) {
            this.jLabel_Registro_NifCorrecto.setText("");
        } else if (nif.length() != 9) {
            this.jLabel_Registro_NifCorrecto.setText("Debe contener 9 caracteres exactos");
            jLabel_Registro_cruz_roja3.setVisible(true);
        } else {
            String numeros = "", letra = "";
            for (int i = 0; i < nif.length() - 1; i++) {
                numeros += nif.charAt(i);
            }
            letra += nif.charAt(8);
            this.jLabel_Registro_NifCorrecto.setText("");
            if (!numeros.matches("[0-9]*")) {
                this.jLabel_Registro_NifCorrecto.setText("Los primeros 8 caracteres deben de ser numeros");
                jLabel_Registro_cruz_roja3.setVisible(true);
            } else if (!letra.matches(".*[A-Z].*")) {
                this.jLabel_Registro_NifCorrecto.setText("El ultimo caracter debe ser una letra mayuscula");
                jLabel_Registro_cruz_roja3.setVisible(true);
            } else {
                this.jLabel_Registro_NifCorrecto.setText("Correcto");
                jLabel_Registro_cruz_roja3.setVisible(false);
                jLabel_Registro_tick_verde3.setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField_Registro_NIFKeyReleased

    private void jTextField_Registro_MunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_MunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_MunicipioActionPerformed

    private void jTextField_Registro_MunicipioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_MunicipioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_MunicipioKeyReleased

    private void jTextField_Registro_Codigo_PostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_Codigo_PostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Codigo_PostalActionPerformed

    private void jTextField_Registro_Codigo_PostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_Codigo_PostalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Codigo_PostalKeyReleased

    private void jTextField_Registro_CalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_CalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_CalleActionPerformed

    private void jTextField_Registro_CalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_CalleKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_CalleKeyReleased

    private void jTextField_Registro_PisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_PisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_PisoActionPerformed

    private void jTextField_Registro_PisoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_PisoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_PisoKeyReleased

    private void jTextField_Registro_PortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_PortalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_PortalActionPerformed

    private void jTextField_Registro_PortalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_PortalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_PortalKeyReleased

    private void jComboBox_Registro_PaísActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Registro_PaísActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Registro_PaísActionPerformed

    private void jComboBox_Registro_CiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Registro_CiudadActionPerformed

    }//GEN-LAST:event_jComboBox_Registro_CiudadActionPerformed

    private void jComboBox_Registro_CiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_Registro_CiudadMouseClicked

    }//GEN-LAST:event_jComboBox_Registro_CiudadMouseClicked

    private void jComboBox_Registro_PaísItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_Registro_PaísItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.jComboBox_Registro_País.getSelectedIndex() >= 0) {
                this.jComboBox_Registro_Ciudad.setModel(new DefaultComboBoxModel(this.getCiudades(this.jComboBox_Registro_País.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_jComboBox_Registro_PaísItemStateChanged

    private void jButton_Registro_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registro_DireccionActionPerformed
        jPanel_Direccion.setEnabled(true);
        jPanel_Direccion.setVisible(true);
        jPanel_Datos_Personales.setEnabled(false);
        jPanel_Datos_Personales.setVisible(false);
        jPanel_Bienvenida.setEnabled(false);
        jPanel_Datos_Bancarios.setEnabled(false);
        jPanel_Datos_Bancarios.setVisible(false);
            jButton_Registro_Empezar.setVisible(false);
        jButton_Registro_Empezar.setEnabled(false);
    }//GEN-LAST:event_jButton_Registro_DireccionActionPerformed

    private void jButton_Registro_Datos_PersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registro_Datos_PersonalesActionPerformed
        jPanel_Datos_Personales.setEnabled(true);
        jPanel_Datos_Personales.setVisible(true);
        jPanel_Bienvenida.setEnabled(false);
        jPanel_Direccion.setEnabled(false);
        jPanel_Direccion.setVisible(false);
        jPanel_Datos_Bancarios.setEnabled(false);
        jPanel_Datos_Bancarios.setVisible(false);
        jButton_Registro_Empezar.setVisible(false);
        jButton_Registro_Empezar.setEnabled(false);
    }//GEN-LAST:event_jButton_Registro_Datos_PersonalesActionPerformed

    private void jButton_Registro_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registro_VolverActionPerformed
        jPanel_Datos_Personales.setEnabled(true);
        jPanel_Datos_Personales.setVisible(true);
        jPanel_Bienvenida.setEnabled(false);
        jPanel_Direccion.setEnabled(false);
        jPanel_Direccion.setVisible(false);
        jPanel_Datos_Bancarios.setEnabled(false);
        jPanel_Datos_Bancarios.setVisible(false);
    }//GEN-LAST:event_jButton_Registro_VolverActionPerformed

    private void jButton_Registro_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registro_SiguienteActionPerformed
        jPanel_Direccion.setEnabled(true);
        jPanel_Direccion.setVisible(true);
        jPanel_Datos_Personales.setEnabled(false);
        jPanel_Datos_Personales.setVisible(false);
        jPanel_Bienvenida.setEnabled(false);
        jPanel_Datos_Bancarios.setEnabled(false);
        jPanel_Datos_Bancarios.setVisible(false);
    }//GEN-LAST:event_jButton_Registro_SiguienteActionPerformed

    private void jButton_Registro_EmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registro_EmpezarActionPerformed
        jPanel_Datos_Personales.setEnabled(true);
        jPanel_Datos_Personales.setVisible(true);
        jPanel_Bienvenida.setEnabled(false);

        jPanel_Direccion.setEnabled(false);
        jPanel_Direccion.setVisible(false);
        jPanel_Datos_Bancarios.setEnabled(false);
        jPanel_Datos_Bancarios.setVisible(false);
            jButton_Registro_Empezar.setVisible(false);
        jButton_Registro_Empezar.setEnabled(false);
    }//GEN-LAST:event_jButton_Registro_EmpezarActionPerformed

    private void jButton_Registro_Datos_BancariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registro_Datos_BancariosActionPerformed
        jPanel_Datos_Bancarios.setEnabled(true);
        jPanel_Datos_Bancarios.setVisible(true);
        jPanel_Datos_Personales.setEnabled(false);
        jPanel_Datos_Personales.setVisible(false);
        jPanel_Bienvenida.setEnabled(false);

        jPanel_Direccion.setEnabled(false);
        jPanel_Direccion.setVisible(false);
            jButton_Registro_Empezar.setVisible(false);
        jButton_Registro_Empezar.setEnabled(false);
    }//GEN-LAST:event_jButton_Registro_Datos_BancariosActionPerformed

    private void jButton_Registro_SuiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registro_SuiguienteActionPerformed
        jPanel_Datos_Bancarios.setEnabled(true);
        jPanel_Datos_Bancarios.setVisible(true);
        jPanel_Datos_Personales.setEnabled(false);
        jPanel_Datos_Personales.setVisible(false);
        jPanel_Bienvenida.setEnabled(false);

        jPanel_Direccion.setEnabled(false);
        jPanel_Direccion.setVisible(false);
    }//GEN-LAST:event_jButton_Registro_SuiguienteActionPerformed

    private void jButton_Registro_Registrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registro_Registrarse1ActionPerformed
        String nombre = this.jTextField_Registro_Nombre.getText();
        String apellido = this.jTextField_Registro_Apellido.getText();
        String email = this.jTextField_Registro_Email.getText();
        String nif = this.jTextField_Registro_NIF.getText();
        String contraseña = "";
        char[] paswrd = this.jPasswordField_Registro_Contraseña.getPassword();
        for (int i = 0; i < paswrd.length; i++) {
            contraseña += paswrd[i];
        }
        String contraseña1 = "";
        char[] paswrd1 = this.jPasswordField_Registro_Contraseña1.getPassword();
        for (int i = 0; i < paswrd1.length; i++) {
            contraseña1 += paswrd1[i];
        }
        String calle = this.jTextField_Registro_Calle.getText();
        String codigopostal = this.jTextField_Registro_Codigo_Postal.getText();
        String ciudad = (String) this.jComboBox_Registro_Ciudad.getSelectedItem();
        String municipio = this.jTextField_Registro_Municipio.getText();
        String pais = (String) this.jComboBox_Registro_País.getSelectedItem();
        String piso = this.jTextField_Registro_Piso.getText();
        String portal = this.jTextField_Registro_Portal.getText();
        String nombretitular = this.jTextField_Registro_Titular_Tarjeta.getText();
        String numerotarjeta = this.jTextField_Registro_Numero_Tarjeta.getText()+this.jTextField_Registro_Numero_Tarjeta1.getText()+this.jTextField_Registro_Numero_Tarjeta2.getText()+this.jTextField_Registro_Numero_Tarjeta3.getText();
        String codigotarjeta = this.jTextField_Registro_Codigo_Tarjeta.getText();
        if ((nombre.isEmpty()) || (apellido.isEmpty()) || (email.isEmpty()) || (nif.isEmpty()) || (contraseña.isEmpty()) || (contraseña1.isEmpty()) || (piso.isEmpty()) || (portal.isEmpty()) || (pais.isEmpty()) || (municipio.isEmpty()) || (calle.isEmpty()) || (ciudad.isEmpty()) || (codigopostal.isEmpty()) || (ciudad == null) || (pais == "--Seleccionar--") || (ciudad == "--Elija País--")) {
            if ((nombre.isEmpty()) && (apellido.isEmpty()) && (email.isEmpty()) && (nif.isEmpty()) && (contraseña.isEmpty()) && (contraseña1.isEmpty()) && (piso.isEmpty()) && (portal.isEmpty())  && (municipio.isEmpty()) && (calle.isEmpty()) && (pais == "--Seleccionar--") && (ciudad == "--Elija País--") && (codigopostal.isEmpty())) {
                JOptionPane.showConfirmDialog(this, "Todos los campos son obligatorios(Excepto la direccion bancaria)", "Información", JOptionPane.CLOSED_OPTION);
            } else {
                if (nombre.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Nombre no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (apellido.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Apellido no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (email.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Email no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (nif.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo NIF no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (contraseña.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Contraseña no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (calle.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Calle no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (portal.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Portal no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (municipio.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Municipio no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (piso.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Piso no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (codigopostal.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo Codigo Postal no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (pais.isEmpty()) {
                    JOptionPane.showConfirmDialog(this, "El campo País no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (ciudad.equals("--Elija País--")|| ciudad == null) {
                    JOptionPane.showConfirmDialog(this, "El campo Ciudad no puede quedar vacío", "Información", JOptionPane.CLOSED_OPTION);
                }
                if (pais.equals("--Seleccionar--")) {
                    JOptionPane.showConfirmDialog(this, "Seleccione un pais", "Información", JOptionPane.CLOSED_OPTION);
                }
               
            }
        } else {
             if(((nombretitular.isEmpty())&&(numerotarjeta.isEmpty())&&(codigotarjeta.isEmpty()))||((!nombretitular.isEmpty())&&(!numerotarjeta.isEmpty())&&(!codigotarjeta.isEmpty()))){
            Boolean nombrevalido = Usuario.validarNombre(nombre);
            Boolean apellidovalido = Usuario.validarApellido(apellido);
            Boolean emailvalido = Usuario.validarEmail(email);
            Boolean nifvalido = Usuario.validarNIF(nif);
            Boolean contraseñavalido = Usuario.contraseñaValida(contraseña);
            Boolean contraseñavalido1 = Usuario.contraseñaValida(contraseña);
            if ((!emailvalido) || (!nifvalido) || (!nombrevalido) || (!apellidovalido) || (!contraseñavalido) || (!contraseñavalido1)) {
                this.jTextField_Registro_Nombre.setText("");
                this.jTextField_Registro_Apellido.setText("");
                this.jTextField_Registro_Email.setText("");
                this.jTextField_Registro_NIF.setText("");
                if (!nombrevalido) {
                    JOptionPane.showMessageDialog(this, "El formato del nombre no es correcto(letras sin numeros ni caracteres especiales)", "Error", JOptionPane.ERROR_MESSAGE);
                }
                if (!apellidovalido) {
                    JOptionPane.showMessageDialog(this, "El formato del apellido no es correcto(letras sin numeros ni caracteres especiales)", "Error", JOptionPane.ERROR_MESSAGE);
                }
                if (!emailvalido) {
                    JOptionPane.showMessageDialog(this, "El formato del email no es correcto(debe contener al menos un @)", "Error", JOptionPane.ERROR_MESSAGE);
                }
                if (!nifvalido) {
                    JOptionPane.showMessageDialog(this, "El formato del NIF no es correcto(debe contener 8 números y una letra mayuscula)", "Error", JOptionPane.ERROR_MESSAGE);
                }
                if (!contraseñavalido) {
                    JOptionPane.showMessageDialog(this, "El formato de la contraseña no es correcto\n(debe contener minimo 8 caracteres,1minuscula,1mayuscula y un caracter especial)", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                Boolean emailbuscado = Usuario.buscarEmail(email);
                Boolean nifbuscado = Usuario.buscarNIF(nif);
                if ((emailbuscado) || (nifbuscado)) {
                    if (emailbuscado) {
                        JOptionPane.showMessageDialog(this, "El Email introducido ya esta registrado", "Error", JOptionPane.ERROR_MESSAGE);
                        this.jTextField_Registro_Email.setText("");
                    }
                    if (nifbuscado) {
                        JOptionPane.showMessageDialog(this, "El NIF introducido ya esta registrado", "Error", JOptionPane.ERROR_MESSAGE);
                        this.jTextField_Registro_NIF.setText("");
                    }
                } else if (!contraseña.equals(contraseña1)) {
                    JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    ArrayList nifsAdministradores = new ArrayList();
                    nifsAdministradores = Usuario.obtenerNIFs("D:\\Users\\DAM101\\Desktop\\Nueva carpeta (2)\\Agencia-conciertos\\Administradores.txt");
                    Boolean esAdmin = false;
                    for (int i = 0; i < nifsAdministradores.size(); i++) {
                        if (nifsAdministradores.get(i).equals(nif)) {
                            esAdmin = true;
                        }
                    }
                    if (!jCheckBox_Registro_Aceptar_Terminos.isSelected()) {
                        JOptionPane.showConfirmDialog(this, "Debe aceptar los terminos y las condiciones de uso", "Información", JOptionPane.CLOSED_OPTION);
                    } else {
                        Usuario nuevousuario = new Usuario(nombre, apellido, email, nif, esAdmin, contraseña);
                        if (esAdmin) {
                            nuevousuario.setAdministrador(true);
                            int confirmar = JOptionPane.showConfirmDialog(this, "¿Esta seguro de que estos son sus datos entonces?\nNOMBRE:" + nombre + "   APELLIDO:" + apellido + "\nEMAIL:" + email + "   NIF:" + nif, "Confirmación", JOptionPane.YES_NO_OPTION);
                            if (confirmar == 0) {
                                String calle1 = calle + " " + portal + " " + piso;
                                Direccion direccion = new Direccion(calle1, codigopostal, pais, ciudad, municipio);
                                DireccionDAO d = new DireccionDAO();
                                d.insertarDireccion(direccion);
                                int idDireccion = DireccionDAO.buscarIDByCalle(calle1);
                       
                                nuevousuario.setIdDireccion(idDireccion);
                                UsuarioDAO u = new UsuarioDAO();
                                u.insertarUsuario(nuevousuario);
                                Inicio inicio = new Inicio();
                                inicio.setVisible(true);
                                this.dispose();
                            } else {
                                this.jTextField_Registro_Nombre.setText("");
                                this.jTextField_Registro_Apellido.setText("");
                                this.jTextField_Registro_Email.setText("");
                                this.jTextField_Registro_NIF.setText("");
                            }
                        } else {
                            nuevousuario.setAdministrador(false);
                            int confirmar = JOptionPane.showConfirmDialog(this, "¿Esta seguro de que estos son sus datos entonces?\nNOMBRE:" + nombre + "   APELLIDO:" + apellido + "\nEMAIL:" + email + "   NIF:" + nif, "Confirmación", JOptionPane.YES_NO_OPTION);
                            if (confirmar == 0) {
                                String calle1 = calle + " " + portal + " " + piso;
                                Direccion direccion = new Direccion(calle1, codigopostal, pais, ciudad, municipio);
                                DireccionDAO d = new DireccionDAO();
                                d.insertarDireccion(direccion);
                                int idDireccion = DireccionDAO.buscarIDByCalle(calle1);
                                Bancario bancario = new Bancario(nombretitular,numerotarjeta,codigotarjeta);
                                BancarioDAO b = new BancarioDAO();
                                b.insertarTarjeta(bancario);
                                int idBancario = BancarioDAO.buscarIDBynumTarjeta(numerotarjeta);
                                nuevousuario.setIdBancario(idBancario);
                                nuevousuario.setIdDireccion(idDireccion);
                                UsuarioDAO u = new UsuarioDAO();
                                u.insertarUsuario(nuevousuario);
                                Inicio inicio = new Inicio();
                                inicio.setVisible(true);
                                this.dispose();
                            } else {
                                this.jTextField_Registro_Nombre.setText("");
                                this.jTextField_Registro_Apellido.setText("");
                                this.jTextField_Registro_Email.setText("");
                                this.jTextField_Registro_NIF.setText("");
                            }
                        }
                    }
                }
                }
                }else{
                 JOptionPane.showConfirmDialog(this, "En caso de introducir un dato bancario,tienes que introducir todos", "Información", JOptionPane.CLOSED_OPTION);
            }
        }
    }//GEN-LAST:event_jButton_Registro_Registrarse1ActionPerformed

    private void jCheckBox_Registro_Aceptar_TerminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_Registro_Aceptar_TerminosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_Registro_Aceptar_TerminosActionPerformed

    private void jButton_Registro_Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registro_Volver1ActionPerformed
        jPanel_Direccion.setEnabled(true);
        jPanel_Direccion.setVisible(true);
        jPanel_Datos_Personales.setEnabled(false);
        jPanel_Datos_Personales.setVisible(false);
        jPanel_Bienvenida.setEnabled(false);
        jPanel_Datos_Bancarios.setEnabled(false);
        jPanel_Datos_Bancarios.setVisible(false);
            jButton_Registro_Empezar.setVisible(false);
        jButton_Registro_Empezar.setEnabled(false);
    }//GEN-LAST:event_jButton_Registro_Volver1ActionPerformed

    private void jTextField_Registro_Titular_TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_Titular_TarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Titular_TarjetaActionPerformed

    private void jTextField_Registro_Titular_TarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_Titular_TarjetaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Titular_TarjetaKeyReleased

    private void jTextField_Registro_Numero_TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_Numero_TarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Numero_TarjetaActionPerformed

    private void jTextField_Registro_Numero_TarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_Numero_TarjetaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Numero_TarjetaKeyReleased

    private void jTextField_Registro_Codigo_TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_Codigo_TarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Codigo_TarjetaActionPerformed

    private void jTextField_Registro_Codigo_TarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_Codigo_TarjetaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Codigo_TarjetaKeyReleased

    private void jTextField_Registro_Numero_Tarjeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_Numero_Tarjeta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Numero_Tarjeta1ActionPerformed

    private void jTextField_Registro_Numero_Tarjeta1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_Numero_Tarjeta1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Numero_Tarjeta1KeyReleased

    private void jTextField_Registro_Numero_Tarjeta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_Numero_Tarjeta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Numero_Tarjeta2ActionPerformed

    private void jTextField_Registro_Numero_Tarjeta2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_Numero_Tarjeta2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Numero_Tarjeta2KeyReleased

    private void jTextField_Registro_Numero_Tarjeta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Registro_Numero_Tarjeta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Numero_Tarjeta3ActionPerformed

    private void jTextField_Registro_Numero_Tarjeta3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Registro_Numero_Tarjeta3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Registro_Numero_Tarjeta3KeyReleased

    public String[] getCiudades(String pais) {
        String[] ciudad = new String[9];
        if (pais.equalsIgnoreCase("España")) {
            ciudad[0] = "Madrid";
            ciudad[1] = "Valencia";
            ciudad[2] = "Barcelona";
            ciudad[3] = "Granada";
            ciudad[4] = "Sevilla";
            ciudad[5] = "Leon";
            ciudad[6] = "Bilbao";
            ciudad[7] = "Zaragoza";
            ciudad[8] = "Cordoba";
        }

        if (pais.equalsIgnoreCase("Andorra")) {
            ciudad[0] = "Andorra la Vieja";
            ciudad[1] = "Encamp";
            ciudad[2] = "Canillo";
            ciudad[3] = "Soldeu";
            ciudad[4] = "El Tarter";
        }

        if (pais.equalsIgnoreCase("Bélgica")) {
            ciudad[0] = "Bruselas";
            ciudad[1] = "Brujas";
            ciudad[2] = "Gante";
            ciudad[3] = "Lieja";

        }

        if (pais.equalsIgnoreCase("Francia")) {
            ciudad[0] = "Paris";
            ciudad[1] = "Paris";
            ciudad[2] = "Toulouse";
            ciudad[3] = "Marsella";
            ciudad[4] = "Lyon";
            ciudad[5] = "Niza";
            ciudad[6] = "Caen";
        }
        if (pais.equalsIgnoreCase("Portugal")) {
            ciudad[0] = "Lisboa";
            ciudad[1] = "Oporto";
            ciudad[2] = "Braga";

        }
        if (pais.equalsIgnoreCase("Alemania")) {
            ciudad[0] = "Berlin";
            ciudad[1] = "Hamburgo";
            ciudad[2] = "Munich";
            ciudad[3] = "Colonia";
            ciudad[4] = "Leipzig";

        }
        if (pais.equalsIgnoreCase("Argentina")) {
            ciudad[0] = "Buenos Aires";
            ciudad[1] = "Rosario";
            ciudad[2] = "La plata";

        }
        if (pais.equalsIgnoreCase("Mexico")) {
            ciudad[0] = "Ciudad de Mexico";
            ciudad[1] = "Merida";
            ciudad[2] = "Cancun";

        }
        return ciudad;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Registro_Datos_Bancarios;
    private javax.swing.JButton jButton_Registro_Datos_Personales;
    private javax.swing.JButton jButton_Registro_Direccion;
    private javax.swing.JButton jButton_Registro_Empezar;
    private javax.swing.JButton jButton_Registro_Registrarse1;
    private javax.swing.JButton jButton_Registro_Siguiente;
    private javax.swing.JButton jButton_Registro_Suiguiente;
    private javax.swing.JButton jButton_Registro_Volver;
    private javax.swing.JButton jButton_Registro_Volver1;
    private javax.swing.JButton jButton_Registro_Volver_Inicio;
    private javax.swing.JCheckBox jCheckBox_Registro_Aceptar_Terminos;
    private javax.swing.JComboBox<String> jComboBox_Registro_Ciudad;
    private javax.swing.JComboBox<String> jComboBox_Registro_País;
    private javax.swing.JLabel jLabe_lRegistro_Linea1;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Registro_Apellido;
    private javax.swing.JLabel jLabel_Registro_ApellidoCorrecto;
    private javax.swing.JLabel jLabel_Registro_Calle;
    private javax.swing.JLabel jLabel_Registro_Codigo_Ciudad;
    private javax.swing.JLabel jLabel_Registro_Codigo_Postal;
    private javax.swing.JLabel jLabel_Registro_Contraseña;
    private javax.swing.JLabel jLabel_Registro_Contraseña1;
    private javax.swing.JLabel jLabel_Registro_ContraseñaCorrecto;
    private javax.swing.JLabel jLabel_Registro_Datos_Opcionales;
    private javax.swing.JLabel jLabel_Registro_Email;
    private javax.swing.JLabel jLabel_Registro_EmailCorrecto;
    private javax.swing.JLabel jLabel_Registro_Fondo;
    private javax.swing.JLabel jLabel_Registro_Linea2;
    private javax.swing.JLabel jLabel_Registro_Linea3;
    private javax.swing.JLabel jLabel_Registro_Linea4;
    private javax.swing.JLabel jLabel_Registro_Linea5;
    private javax.swing.JLabel jLabel_Registro_Linea6;
    private javax.swing.JLabel jLabel_Registro_Linea7;
    private javax.swing.JLabel jLabel_Registro_Municipio;
    private javax.swing.JLabel jLabel_Registro_NIF;
    private javax.swing.JLabel jLabel_Registro_NifCorrecto;
    private javax.swing.JLabel jLabel_Registro_NombreCorrecto;
    private javax.swing.JLabel jLabel_Registro_Numero_Tarjeta;
    private javax.swing.JLabel jLabel_Registro_Pais;
    private javax.swing.JLabel jLabel_Registro_Piso;
    private javax.swing.JLabel jLabel_Registro_Portal;
    private javax.swing.JLabel jLabel_Registro_Titular_Codigo_Tarjeta;
    private javax.swing.JLabel jLabel_Registro_Titular_Tarjeta;
    private javax.swing.JLabel jLabel_Registro_cruz_roja;
    private javax.swing.JLabel jLabel_Registro_cruz_roja1;
    private javax.swing.JLabel jLabel_Registro_cruz_roja2;
    private javax.swing.JLabel jLabel_Registro_cruz_roja3;
    private javax.swing.JLabel jLabel_Registro_cruz_roja4;
    private javax.swing.JLabel jLabel_Registro_cruz_roja5;
    private javax.swing.JLabel jLabel_Registro_tick_verde1;
    private javax.swing.JLabel jLabel_Registro_tick_verde2;
    private javax.swing.JLabel jLabel_Registro_tick_verde3;
    private javax.swing.JLabel jLabel_Registro_tick_verde4;
    private javax.swing.JLabel jLabel_Registro_tick_verde5;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_tick_verde;
    private javax.swing.JLabel jLabel_tick_verde6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Bienvenida;
    private javax.swing.JPanel jPanel_Datos_Bancarios;
    private javax.swing.JPanel jPanel_Datos_Personales;
    private javax.swing.JPanel jPanel_Direccion;
    private javax.swing.JPasswordField jPasswordField_Registro_Contraseña;
    private javax.swing.JPasswordField jPasswordField_Registro_Contraseña1;
    private javax.swing.JTextField jTextField_Registro_Apellido;
    private javax.swing.JTextField jTextField_Registro_Calle;
    private javax.swing.JTextField jTextField_Registro_Codigo_Postal;
    private javax.swing.JTextField jTextField_Registro_Codigo_Tarjeta;
    private javax.swing.JTextField jTextField_Registro_Email;
    private javax.swing.JTextField jTextField_Registro_Municipio;
    private javax.swing.JTextField jTextField_Registro_NIF;
    private javax.swing.JTextField jTextField_Registro_Nombre;
    private javax.swing.JTextField jTextField_Registro_Numero_Tarjeta;
    private javax.swing.JTextField jTextField_Registro_Numero_Tarjeta1;
    private javax.swing.JTextField jTextField_Registro_Numero_Tarjeta2;
    private javax.swing.JTextField jTextField_Registro_Numero_Tarjeta3;
    private javax.swing.JTextField jTextField_Registro_Piso;
    private javax.swing.JTextField jTextField_Registro_Portal;
    private javax.swing.JTextField jTextField_Registro_Titular_Tarjeta;
    // End of variables declaration//GEN-END:variables
}
